### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set a background color for the car to drive on.
- [x] Add a square image to represent the car.
- [x] Make sure the car is on the top right corner.
- [x] The front of the car should be pointed to the right.
- [x] Make sure the car appears when the page is loaded.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
