### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model for car direction.
- [x] Add event listeners for keydown event.
- [x] Store keydown value in data model if value if up, down, left or right arrow.
- [x] Create CSS classes for each direction using rotate and add a slight delay to the movement.
- [x] Within the event listeners function, update the direction according the the pressed key updating the image class attribute.
