### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add `absolute positioning` to the image elements.
- [x] Add a location object to your data model to hold the car's `x` and `y` coordinates (as properties) on the page.
- [x] Add an event listener for the `space` keydown to start the car.
- [x] Move the car every 16 milliseconds using `setInterval( )` within the event listener function.
- [x] Use the `style` property of element objects to change your car's `top` and `left` box offset styles.
- [x] Update the location object with the `top` and `left` values.
