### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Create a variable called `startStop` for each time `space` is pressed.
- [x] Update the event listener to check if `startStop` is even or odd.
- [x] If `startStop` is even, start the car. Else, stop the car.
