### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update function moveCar to check the value of `car.direction` the car is pointed.
- [x] Update function moveCar style the image class according to `car.direction`.
- [x] Update function moveCar to increment and decrement for the `x` and `y` values.
- [x] Remove unused CSS selectors and fix bugs.
